import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/componentZ/Nav";
import Footer from "@/componentZ/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" mt-10 mb-10 mr-20 ml-20 ">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
         
       
        <Nav></Nav>
        {children}
        <Footer></Footer>


      </body>
    </html>
  );
}
